language: csharp
mono: none
dotnet: 2.2
dist: xenial
script:
  - dotnet build ./src/Montr.sln
  - dotnet test ./src/Montr.sln
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
