version: '3'
services:
  host:
    container_name: montr_host
    image: montr/host
    restart: always
    ports:
    - "5000:5000"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://+:5000;
    #- Montr.Core.AppOptions:AppUrl=https://app.montr.io:5001
    #- Montr.Core.AppOptions:CookieDomain=.montr.io
    - ConnectionString:Name=Default
    - ConnectionString:ProviderName=PostgreSQL
    - ConnectionStrings:Default=Server=db;Port=5432;Database=host;User Id=postgres;
    - Montr.Core.MigrationOptions:MigrationPath=./database/migrations
    depends_on:
    - db
  db:
    container_name: montr_db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: host
    # ports:
    # - "5435:5432"
    volumes:
      - montr_db_dev:/var/lib/postgresql/data
volumes:
  montr_db_dev:
