name: build
env:
  ConnectionStrings:Default: Server=localhost;Port=5432;Database=host;User Id=postgres;Password=secret;
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: host
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'

      - run: dotnet build ./src/Montr.sln

      - run: dotnet test ./src/Montr.Core.Tests

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: |
          npm ci
          npm run build-prod
          # - run: npm test
        working-directory: ./src/ui
