name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # checkout
      - uses: actions/checkout@master

      # build dotnet
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
      - run: dotnet build ./src/Montr.sln

      # build node
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build-prod
      - working-directory: ./src/ui
      # - run: npm test
