name: build
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'

      - run: dotnet build ./src/Montr.sln

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: |
          npm ci
          npm run build-prod
          # - run: npm test
        working-directory: ./src/ui
